repos:

 
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: ["--ignore-words=./doc/styles/Vocab/LAMBERTHUB/accept.txt"]
