version: 2
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
sphinx:
  builder: html
  configuration: doc/source/conf.py
  fail_on_warning: true
