[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lamberthub"
readme = "README.md"
license = {file = "LICENSE" }
requires-python = ">=3.8"
authors = [
    {name = "Jorge Martínez Garrido", email = "jorge@on-orbit.dev" }
]
keywords = [
    "aerospace",
    "astrodynamics",
    "orbital-mechanics",
    "kepler",
    "lambert",
    "orbit-determination",
]
author-email = "jorge@on-orbit.dev"
home-page = "https://github.com/jorgepiloto/lamberthub"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = ["cmaps", "matplotlib", "numpy", "scipy"]
dynamic = ["version", "description"]

[project.urls]
Source = "https://github.com/jorgepiloto/lamberthub"
Tracker = "https://github.com/jorgepiloto/lamberthub/issues"

[project.optional-dependencies]
dev = [
    "black",
    "coverage",
    "isort",
    "jupytext",
    "myst-nb",
    "nbsphinx",
    "notebook",
    "pycodestyle",
    "pytest>=3.2",
    "pytest-cov<2.6.0",
    "pytest-doctestplus>=0.8",
    "pytest-mpl",
    "sphinx",
    "sphinx-autoapi",
    "sphinx-gallery",
    "sphinx-rtd-theme",
    "tox",
]

[tool.flit.sdist]
exclude = [
    "docs/",
    "tests",
    "art/",
]
