[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lamberthub"
readme = "README.md"
license = {file = "LICENSE" }
requires-python = ">=3.7"
authors = [
    {name = "Jorge Martínez Garrido", email = "jorge@astrodevelopers.com" }
]
maintainers = [
    {name = "Jorge Martínez Garrido", email = "jorge@astrodevelopers.com" }
]
keywords = [
    "aerospace",
    "astrodynamics",
    "orbital-mechanics",
    "kepler",
    "lambert",
    "orbit-determination",
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = ["cmaps", "matplotlib", "numpy", "scipy"]
dynamic = ["version", "description"]

[project.urls]
Source = "https://github.com/jorgepiloto/lamberthub"
Tracker = "https://github.com/jorgepiloto/lamberthub/issues"

[project.optional-dependencies]
tests = [
    "pytest>=7.1.2",
    "pytest-cov>=3.0.0",
    "pytest-mpl>=0.15.1",
]
doc = [
    "furo>=2022.4.7",
    "jupytext>=1.13.8",
    "myst-nb>=0.14.0",
    "nbsphinx>=0.8.8",
    "notebook>=6.4.11",
    "sphinx>=4.5.0",
    "sphinx-autoapi>=1.8.4",
    "sphinx-gallery>=0.10.1",
]

[tool.flit.sdist]
exclude = [
    "docs/",
    "tests",
    "art/",
]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 79
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests"]

[tool.coverage.run]
source = ["lamberthub"]

[tool.coverage.report]
show_missing = true
