name: Docs
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "*"
    branches:
      - main
  repository_dispatch:

jobs:


  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get install pandoc texlive
          python -m pip install --upgrade pip tox
      - name: Generate the documentation with tox
        run: tox -e doc

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v2
        with:
          name: HTML-Documentation
          path: .tox/doc_out

      - name: Deploy
        run: |
          curl -XPOST -u "${{ secrets.USERNAME }}:${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/jorgepiloto/jorgepiloto.github.io/actions/workflows/publish.yml/dispatches \
          --data '{"ref": "main"}' \
          --fail
